version: "3.5"

services:
  db:
    image: postgres
    container_name: postgresql
    restart: always
    working_dir: /root
    env_file:
      - .env
    volumes:
      - .:/root
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres_net
networks:
  postgres_net:
    name: postgres_net
    driver: bridge
